`element-session` design and packaging
datajoint/element-session pull request #1
Opened 2021-03-22 21:17 UTC by ttngu207

2021-03-22 21:41 UTC, shenshan requested changes

2021-03-22 21:41 UTC, shenshan commented on element_session/session.py
> +class SessionDirectory(dj.Manual):
Shall we put it as a part table as we did in the workflow? Are there any new design considerations here?

2021-03-22 21:41 UTC, shenshan commented on element_session/session.py
> +    session_dir: varchar(256)       # Path to the data directory for a particular session
Is this duplication to `session_dir` in SessionDirectory?
Can we put Project as part table of Session as well?

2021-03-22 21:41 UTC, shenshan commented on element_session/session.py
> +    session_dir: varchar(256)       # Path to the data directory for a particular session
Is this a left over? I saw another Project later on.

2021-03-22 21:41 UTC, shenshan commented on element_session/session.py
> +        ---
One project one publication?

2021-03-22 21:41 UTC, shenshan commented on element_session/session.py
> +    -> Session
Consider putting Project as a part table in Session.

2021-03-22 21:44 UTC, ttngu207 commented on element_session/session.py
> +    session_dir: varchar(256)       # Path to the data directory for a particular session
ah, yes, left over from copy-paste error, thanks for the catch. PR updated

2021-03-22 21:46 UTC, ttngu207 commented on element_session/session.py
> +    -> Session
Following our DataJoint principle, all parts must be inserted along with master, making this a part table would be difficult to uphold that principle, as users often associate the sessions to particular project after the project is created (on-going work)

2021-03-22 21:49 UTC, ttngu207 commented on element_session/session.py
> +class SessionDirectory(dj.Manual):
One argument against the part-table design is that, if users need to change the directory, using the "delete and reinsert" approach, they wouldn't be able to delete just the part-table without deleting the master

2021-03-22 22:07 UTC, ttngu207 commented on element_session/session.py
> +        ---
This is up for debate, but I'm thinking that if there's another publication, then users would just need to create another project
Otherwise it'd make more sense to create a separate `ProjectPublication` table

2021-03-23 00:09 UTC, kabilar commented on README.md
> +# DataJoint Element - Animal
```suggestion
# DataJoint Element - Session
```

2021-03-23 00:15 UTC, kabilar commented on README.md
> + and [workflow-ephys](https://github.com/datajoint/workflow-ephys) repositories for example usages of `element-session`.
```suggestion
+ See the [workflow-calcium-imaging](https://github.com/datajoint/workflow-calcium-imaging)
 and [workflow-array-ephys](https://github.com/datajoint/workflow-array-ephys) repositories for example usages of `element-session`.
```

2021-03-23 00:16 UTC, kabilar commented on setup.py
> +DataJoint Elements for Session Management
```suggestion
DataJoint Element for Session Management
```

2021-03-23 00:17 UTC, kabilar commented on setup.py
> +    author_email='info@vathes.com',
Do we have a DataJoint NEURO email address?

2021-03-23 01:07 UTC, shenshan commented on element_session/session.py
> +class Project(dj.Manual):
Just realized that Project is covered in element-lab as well.

2021-03-23 01:14 UTC, kabilar commented on element_session/session.py
> +    session_dir: varchar(256)       # Path to the data directory for a particular session
```suggestion
    session_dir: varchar(256)       # Relative path to the data directory for a particular session
```

2021-03-23 01:27 UTC, kabilar approved these changes

2021-03-23 01:30 UTC, kabilar requested changes
Great work.  Few minor fixes requested.

2021-03-23 01:38 UTC, dimitri-yatsenko commented on element_session/session.py
> +    -> Session
It's the same argument as for using updates. They should not be part of a regular process but can be used for fixing things.

2021-03-23 01:41 UTC, dimitri-yatsenko approved these changes

2021-03-23 01:42 UTC, dimitri-yatsenko commented
Add `Background.md`? Or next PR?

2021-03-23 16:42 UTC, kabilar approved these changes

2021-03-23 16:43 UTC, shenshan approved these changes

2021-03-23 16:43 UTC, merged