[DRAFT] Add mkdocs
datajoint/element-session pull request #26
Opened 2022-10-25 23:55 UTC by sidhulyalkar

2022-10-27 23:08 UTC, kabilar requested changes
Thanks @sidhulyalkar.  Please update the `index` and `concepts` pages to reflect the latest structure and narrative from [element-deeplabcut](https://datajoint.com/docs/elements/element-deeplabcut/0.2/).

2022-10-27 23:08 UTC, kabilar commented on docs/src/index.md
> +estimation
```suggestion
```

2022-10-28 14:25 UTC, CBroz1 commented
Please add [automated versioning to the citation page](https://github.com/datajoint/element-deeplabcut/commit/352c44f98325cb79a249026d84310bff8417e7e2)

2022-10-28 21:43 UTC, CBroz1 commented
replaced by #27

2022-10-28 21:43 UTC, closed without merging